name: "Setup CIntent"
description: "Set up your GitHub Actions job for CIntent."
author: "Javid Ditty"
branding:
  icon: "eye"
  color: "orange"
runs:
  using: "composite"
  steps:
    - name: Set Environmental Variables
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        CINTENT_ARTIFACT_NAME="$(date +%s%N)-cintent_logs"
        echo "CINTENT_ARTIFACT_NAME=$CINTENT_ARTIFACT_NAME" >> $GITHUB_ENV

        CINTENT_BASH=/home/runner/cintent/bin/bash
        echo "CINTENT_BASH=$CINTENT_BASH" >> $GITHUB_ENV

        CINTENT_BIN=/home/runner/cintent/bin
        echo "CINTENT_BIN=$CINTENT_BIN" >> $GITHUB_ENV
        mkdir -p $CINTENT_BIN

        CINTENT_GETHOSTNAME=${{ github.action_path }}/tools/gethostname.bt
        echo "CINTENT_GETHOSTNAME=$CINTENT_GETHOSTNAME" >> $GITHUB_ENV

        CINTENT_LOGS=/home/runner/cintent/log
        echo "CINTENT_LOGS=$CINTENT_LOGS" >> $GITHUB_ENV
        mkdir -p $CINTENT_LOGS

        CINTENT_PYFUNCTIONS=${{ github.action_path }}/bin/pyfunctions
        echo "CINTENT_PYFUNCTIONS=$CINTENT_PYFUNCTIONS" >> $GITHUB_ENV

        CINTENT_PYPSNOOP=${{ github.action_path }}/tools/pypsnoop.bt
        echo "CINTENT_PYPSNOOP=$CINTENT_PYPSNOOP" >> $GITHUB_ENV

        CINTENT_PYPSNOOP_SH=${{ github.action_path }}/tools/pypsnoop.sh
        echo "CINTENT_PYPSNOOP_SH=$CINTENT_PYPSNOOP_SH" >> $GITHUB_ENV

        CINTENT_PYSPY=${{ github.action_path }}/bin/py-spy
        echo "CINTENT_PYSPY=$CINTENT_PYSPY" >> $GITHUB_ENV

        CINTENT_STEP_ID=0
        echo "CINTENT_STEP_ID=$CINTENT_STEP_ID" >> $GITHUB_ENV

        CINTENT_TCPLIFE=${{ github.action_path }}/tools/tcplife.bt
        echo "CINTENT_TCPLIFE=$CINTENT_TCPLIFE" >> $GITHUB_ENV

    - name: Parse Python Functions
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        ${{ env.CINTENT_PYFUNCTIONS }} -o ${{ env.CINTENT_LOGS }} ${{ github.workspace }}

    - name: Write Bash Wrappers
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        # Save the current matrix configurations
        echo "${{ toJson(matrix) }}" > matrix_context.json
        CINTENT_MATRIX=$(cat matrix_context.json | tr -s '\n' ' ')
        echo "CINTENT_MATRIX=$CINTENT_MATRIX" >> $GITHUB_ENV

        # Write the bash wrapper
        cat << 'WRAPPER_EOF' > ${{ env.CINTENT_BASH }}
        #!/bin/bash
        if [[ -z "${CINTENT_IS_TRACING_BASH}" ]]; then
          # Set tracer indicator
          export CINTENT_IS_TRACING_BASH=true
          echo "CINTENT_IS_TRACING_BASH=$CINTENT_IS_TRACING_BASH" >> $GITHUB_ENV

          # Increment the step id
          CINTENT_STEP_ID=$((CINTENT_STEP_ID+1))
          echo "CINTENT_STEP_ID=$CINTENT_STEP_ID" >> "$GITHUB_ENV"
          
          # Define the log paths
          timestamp=$(date +%s%N)
          metadata_log=$CINTENT_LOGS/$timestamp.$CINTENT_STEP_ID.metadata.txt
          execsnoop_log=$CINTENT_LOGS/$timestamp.$CINTENT_STEP_ID.execsnoop.txt
          gethostname_log=$CINTENT_LOGS/$timestamp.$CINTENT_STEP_ID.gethostname.txt
          opensnoop_log=$CINTENT_LOGS/$timestamp.$CINTENT_STEP_ID.opensnoop.txt
          tcplife_log=$CINTENT_LOGS/$timestamp.$CINTENT_STEP_ID.tcplife.txt
          
          # Create the metadata log
          echo -en \
          "repository = $GITHUB_REPOSITORY\n"\
          "branch = $GITHUB_REF_NAME\n"\
          "commit = $GITHUB_SHA\n"\
          "workflow = ${GITHUB_WORKFLOW_REF%@*}\n"\
          "run_number = $GITHUB_RUN_NUMBER\n"\
          "run_attempt = $GITHUB_RUN_ATTEMPT\n"\
          "workspace = $GITHUB_WORKSPACE\n"\
          "job_id = $GITHUB_JOB\n"\
          "matrix = $CINTENT_MATRIX\n"\
          "step_id = $CINTENT_STEP_ID\n"\
          > "$metadata_log"
          sed -i 's/^[ ]*//' "$metadata_log"

          # Start snooping tools and pipe their outputs to their logs
          export BPFTRACE_MAX_STRLEN=200
          sudo --preserve-env=BPFTRACE_MAX_STRLEN bpftrace "${{ env.CINTENT_GETHOSTNAME }}" > "$gethostname_log" 2> /dev/null &
          sudo --preserve-env=BPFTRACE_MAX_STRLEN bpftrace "${{ env.CINTENT_TCPLIFE }}" > "$tcplife_log" 2> /dev/null &
          sudo --preserve-env=BPFTRACE_MAX_STRLEN,CINTENT_LOGS,CINTENT_PYPSNOOP,CINTENT_PYPSNOOP_SH,CINTENT_PYSPY,CINTENT_STEP_ID bpftrace --unsafe "${{ env.CINTENT_PYPSNOOP }}" &> /dev/null &
          sudo execsnoop-bpfcc -qtx --max-args 100 > "$execsnoop_log" 2> /dev/null &
          sudo opensnoop-bpfcc -eT > "$opensnoop_log" 2> /dev/null &
          
          # Wait for snooping tools to start tracing (or timeout)
          timeout_time=60
          start_time=$SECONDS
          current_time=$((SECONDS - start_time))
          execsnoop_search="TIME(s)\s+PCOMM\s+PID\s+PPID\s+RET\s+ARGS"
          opensnoop_search="TIME(s)\s+PID\s+COMM\s+FD\s+ERR\s+FLAGS\s+PATH"
          until grep -q "$execsnoop_search" "$execsnoop_log" && grep -q "$opensnoop_search" "$opensnoop_log" || [[ "$current_time" -gt "$timeout_time" ]]; do
            sleep 1
            current_time=$((SECONDS - start_time))
          done
          if grep -q "$execsnoop_search" "$execsnoop_log"; then
            echo "execsnoop failed to start!" 1>&2
            exit 1
          fi
          if grep -q "$opensnoop_search" "$opensnoop_log"; then
            echo "opensnoop failed to start!" 1>&2
            exit 1
          fi

          # (Re-)Apply the wrapper(s)
          export PATH="${{ env.CINTENT_BIN }}:$PATH"
          echo ${{ env.CINTENT_BIN }} >> $GITHUB_PATH

          # Start the bash script
          echo "start_time = $(date +%s)" >> $metadata_log
          /bin/bash "$@"
          echo "end_time = $(date +%s)" >> $metadata_log

          # (Re-)Apply the wrapper(s)
          export PATH="${{ env.CINTENT_BIN }}:$PATH"
          echo ${{ env.CINTENT_BIN }} >> $GITHUB_PATH

          # Unset tracer indicator
          unset CINTENT_IS_TRACING_BASH
          echo "CINTENT_IS_TRACING_BASH=" >> $GITHUB_ENV
        else
          # (Re-)Apply the wrapper(s)
          export PATH="${{ env.CINTENT_BIN }}:$PATH"
          echo ${{ env.CINTENT_BIN }} >> $GITHUB_PATH

          # Start the bash script
          /bin/bash "$@"

          # (Re-)Apply the wrapper(s)
          export PATH="${{ env.CINTENT_BIN }}:$PATH"
          echo ${{ env.CINTENT_BIN }} >> $GITHUB_PATH
        fi
        WRAPPER_EOF
        chmod +x ${{ env.CINTENT_BASH }}

    - name: Apply Wrappers
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        export PATH="${{ env.CINTENT_BIN }}:$PATH"
        echo ${{ env.CINTENT_BIN }} >> $GITHUB_PATH
